### ISSUE TITLE
enhance hopspot settings

### ISSUE THREAD

**Issue by domx4q** [domx4q/astroProject#66]
### First possible date
Kann erst ab der ersten Dezember Woche angefangen werden, da uns dann die PRO Version von FormKit zur verfügung steht, welche viele Vorteile hat
[Check FormKit Status](https://pro.formkit.com/early-access?email=ev3dom%40gmx.de)
### Todo's

- [ ] [maybe] autosave (speak with  @CraftermanL)
- [ ] change classification to taglist from new FormKit Release
- [ ] extra add Method without holding alt
- [ ] [maybe] move hospots or edit or delete
